- name: Deploy to Tomcat WebServer
  hosts: all
  become: true
  vars:
          directory_name: working_directory
  tasks:
          - name: create working directory
            file:
                path: "{{ directory_name }}"
                state: directory
          - name: Installing tomcat
            apt:
                name: tomcat9
                state: latest
          - name: Starting tomcat server
            service:
                name: tomcat9
                state: started
          - name: Install maven
            apt:
                name: maven
                state: present
          - name: git checkout
            git:
                repo: 'https://github.com/SayamGanguly/java-tomcat-maven-example.git'
                dest: "{{ directory_name }}"
          - name: Build the WebApp
            command: mvn -f "{{ directory_name }}"/pom.xml package
          - name: Deploy WebApp on tomcat Server
            copy:
                src: /home/labsuser/working_directory/target/java-tomcat-maven-example.war
                dest: /var/lib/tomcat9/webapps/java-tomcat-maven-example.war
          - name: Restarting tomcat server
            service:
                name: tomcat9
                state: restarted
