- name: Testing ping module
  hosts: all
  become: true
  vars:
          directory_name: working_directory_1
  tasks:
          - name: create working directory
            file:
                path: "{{ directory_name }}"
                state: directory
          - name: installing tomcat9
            apt:
                name: tomcat9
                state: latest
          - name: starting tomcat9 service
            service:
                name: tomcat9
                state: started
          - name: install maven
            apt:
                name: maven
                state: present
          - name: git checkout
            git:
                repo: 'https://github.com/SayamGanguly/java-tomcat-maven-example.git'
                dest: "{{ directory_name }}"
          - name: register ls result
            command: ls
            register: res
          - name: display result
            debug:
                msg: "{{ res.stdout }}"
          - name: run mvn package
            command: mvn -f "{{ directory_name }}"/pom.xml package
          - name: Deploy war file
            copy:
                src: /home/labsuser/working_directory_1/target/java-tomcat-maven-example.war
                dest: /var/lib/tomcat9/webapps/java-tomcat-maven-example.war
          - name: Restarting tomcat9
            service:
                name: tomcat9
                state: restarted
